name: Build all images

on:
  push:
    branches:
      - main

# We need to match our permissions of our docker-build.yaml
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

# TODO: How do we properly rebuild images when build-all-images.yaml itself is changed?
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      php_files: ${{ steps.filter.outputs.php_files }}
      php: ${{ steps.filter.outputs.php }}
      unit_files: ${{ steps.filter.outputs.unit_files }}
      unit: ${{ steps.filter.outputs.unit }}
      frankenphp_files: ${{ steps.filter.outputs.frankenphp_files }}
      frankenphp: ${{ steps.filter.outputs.frankenphp }}
      general: ${{ steps.filter.outputs.general }}
      general_matrix: ${{ steps.general-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2

      - name: Get previous commit SHA to correctly detect changed files
        run: echo "PREVIOUS_COMMIT_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

      - name: Detect changed Dockerfiles
        id: filter
        uses: dorny/paths-filter@v4
        with:
          base: ${{ env.PREVIOUS_COMMIT_SHA }}
          list-files: json
          filters: |
            php:
              - 'php/*.Dockerfile'
            unit:
              - 'unit/*.Dockerfile'
            frankenphp:
              - 'frankenphp/*.Dockerfile'
            general:
              - '*.Dockerfile'

      - name: Strip out .Dockerfile suffix from all generic images so we can easily run a matrix job
        id: general-matrix
        env: # Protect against injection attacks
          FILES: ${{ steps.filter.outputs.general_files }}
        run: |
          matrix=$(jq -c '[.[] | {
            file:        .,
            image:       (. | sub("\\.Dockerfile$"; "")),
            dockerfiles: ([.] | tostring)
          }]' <<<"$FILES")
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build-php:
    needs: changes
    if: needs.changes.outputs.php == 'true'
    uses: ./.github/workflows/call-docker-build.yaml
    with:
      image: php
      dockerfiles: ${{ needs.changes.outputs.php_files }}
      variants: '["-fpm"]'
      # NOTES:
      # - ghostscript is often used by WordPress which we are using a lot
      build-args: &php-build-args |
        DEBIAN_PACKAGES=msmtp-mta less ghostscript
        PHP_EXTENSIONS=redis gd bcmath exif intl mysqli pgsql pdo_mysql pdo_pgsql zip imagick opcache

  build-unit:
    needs: changes
    if: needs.changes.outputs.unit == 'true'
    uses: ./.github/workflows/call-docker-build.yaml
    with:
      image: unit
      dockerfiles: ${{ needs.changes.outputs.unit_files }}
      build-args: *php-build-args

  build-frankenphp:
    needs: changes
    if: needs.changes.outputs.frankenphp == 'true'
    uses: ./.github/workflows/call-docker-build.yaml
    with:
      image: frankenphp
      dockerfiles: ${{ needs.changes.outputs.frankenphp_files }}
      build-args: *php-build-args

  # Special job to run build for all *.Dockerfile in this repository
  build:
    needs: changes
    if: needs.changes.outputs.general == 'true'
    concurrency:
      group: build-general-${{ matrix.target.image }}
      cancel-in-progress: true
    name: ${{ matrix.target.image }} - ${{ matrix.target.file }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.changes.outputs.general_matrix) }}
    uses: ./.github/workflows/call-docker-build.yaml
    with:
      image: ${{ matrix.target.image }}
      dockerfiles: ${{ matrix.target.dockerfiles }}
